@isTest
public class ClientDeclarationDetailsTest {
   // @isTest
    //public static void ClientDeclarationDetailMethod{
        
    ClientDeclarationDetails clientDetails = new ClientDeclarationDetails();
    //SELECT Id, BankStatus__c from Account where RecordTypeId = \'' + AccountRecordTypeId + '\''; 
    //clientDetails.ClientId = '';
        
            //ClientDeclarationDetails.ClientId = 'a0M290000022ngIEAQ';
            //clientDetails.ClientFirstName = 'Jojo';
            //ClientDeclarationDetails.ClientLastName = 'Sams';
            //ClientDeclarationDetails.ClientFullName = 'Jojo Sams';
            //ClientDeclarationDetails.ClientDeclarationStatus = true;    
    	//System.assertEquals(ClientDeclarationDetails.ClientFirstName, 'Jojo');
    //}
           
}