public class ConditionResponse {
 
     @AuraEnabled public   String  Id { get;set; }
    @AuraEnabled public   String  Index { get;set; }
    @AuraEnabled public   String  DescText { get;set; }
    @AuraEnabled public   String  DropDownValue { get;set; }
     @AuraEnabled public  string  Status { get;set; } 
     @AuraEnabled public  string  CreatedDate { get;set; } 
     @AuraEnabled public  string  StatusDate { get;set; } 
     @AuraEnabled public  string  CreatedBy { get;set; } 
     @AuraEnabled public  string  LastModifyBy { get;set; } 
    @AuraEnabled public  string  LastModifyDate { get;set; } 
     @AuraEnabled public  string  NewDescText { get;set; } 
     @AuraEnabled public  string  NewStatus { get;set; } 
    
    
 	
}