public class PipelineConditionResponse {
    
    @AuraEnabled public  string  Id { get;set; }
    @AuraEnabled public  string  ApplicationDate { get;set; }
    @AuraEnabled public  string  Status { get;set; } 
    @AuraEnabled public  string  PCS_Name  { get;set; }
    @AuraEnabled public  string  PhoneNumber { get;set; } 
    @AuraEnabled public  string  TodaysDate { get;set; }
    @AuraEnabled public  string  ClientName { get;set; }
     @AuraEnabled public  string  LoanNumberorId { get;set; }
}