public class PipeLineDetailsResponse {
 @AuraEnabled public   Id Loanid { get;set; }
    @AuraEnabled public   String LoanNumberDetails { get;set; }     
    @AuraEnabled public   String  FullName { get;set; }
    @AuraEnabled public   String  LoanStatus { get;set; }
    @AuraEnabled public   String  Address { get;set; }
     @AuraEnabled public  string  Phone { get;set; }
     @AuraEnabled public  string  CPhone { get;set; }
     @AuraEnabled public  string  DOB { get;set; }
     @AuraEnabled public  string  CreatedBy { get;set; }
    @AuraEnabled public   string  LoanDate { get;set; }
     @AuraEnabled public   string  Email { get;set; }
    @AuraEnabled public string ContactEmail{get;set;}
    
}