public class PricingResponse {
    @AuraEnabled public string Margin{get;set;}
    @AuraEnabled public string x0_to_10{get;set;}
    @AuraEnabled public string x10_to_20{get;set;}
    @AuraEnabled public string x20_to_30{get;set;}
    @AuraEnabled public string x30_to_40{get;set;}
    @AuraEnabled public string x40_to_50{get;set;}
    @AuraEnabled public string x50_to_60{get;set;}
    @AuraEnabled public string x60_to_70{get;set;}
    @AuraEnabled public string x70_to_80{get;set;}
    @AuraEnabled public string x80_to_90{get;set;}
    @AuraEnabled public string x90_to_100{get;set;}
    
}