public  class ScenarioResponse
{
    
    public List<string> priority { get; set; }
    public string modelType { get; set; }
    public string annualLiborChangeDate { get; set; }
    public double annualMIP { get; set; }
    public double lendersMargin { get; set; }
    public double growthRateInitial { get; set; }
    public double growthRateAverage10yr { get; set; }
    public double growthRateAverage20yr { get; set; }
    public double apr { get; set; }
    public double annualLibor { get; set; }
    
  

     
}