{
    "requestIdentifer": "31f9d587-063f-48ec-8077-1144a825ad26",
    "parsedRequest": {
        "requestIdentifier": "31f9d587-063f-48ec-8077-1144a825ad26",
        "reference": "MOCKREFERENCE123",
        "meta": [],
        "property": {
            "zipCode": "48390",
            "transactionType": "Refinance",
            "loanAmount": 500000,
            "propertyType": {
                "_val": 0
            },
            "loanType": {
                "_val": 4
            }
        },
        "title": {
            "productType": "Title Commitment",
            "policy": "Mortgage Policy",
            "refiExistingMortgage": true,
            "refiSameLender": false
        },
        "closing": {
            "lienType": "First Lien",
            "prepareDeed": true
        },
        "recording": {
            "fees": [
                "Deed",
                "Mortgage"
            ],
            "numDeedPages": 4,
            "considerationAmount": "500000",
            "numMortgagePages": 28,
            "newDebtAmount": "750000"
        }
    }
}
